### ISSUE TITLE
Herald stops working again!!!

### ISSUE THREAD

**Issue by StanleyXenon** [Xjph/observatory-docs#6]
Observatory has been working fine since the last update. Today for no reason Herald does not work.

It doesn't show under core plug ins,  the Data file folder for Herald is empty, the plug in folder has the .dll file

I have completely uninstalled Observatory removing the Data and plugin folders using bot the Observatory uninstaller and the a 3rd party one. I've cleaned my registry and restarted my machine  a number of times, and nothing

I've finally given up and playing with it in silence and using ED Buddy for voice.

**Comment by Xjph** [comment]
[Herald is offline](https://forums.frontier.co.uk/threads/elite-observatory-search-your-journal-for-potentially-interesting-objects-or-notify-you-of-new-ones-on-the-fly-while-exploring.521544/post-10485312) due to hosting costs associated with the cloud-based voice synthesis it used.

Also, this is not the correct repository for reporting [issues with Observatory.](https://github.com/Xjph/ObservatoryCore/issues).
