### ISSUE TITLE
EO Fails to launch after update

### ISSUE THREAD

**Issue by BannorPhil** [Xjph/observatory-docs#7]
I updated EO to 1.1.4 from a recent version (can't remember which exactly), and after installation it fails to launch. No error message, no nothing. Tried uninstalling, reinstalling (several versions from 1.1.1) -  nothing. Run as Admin - still nothing.
Windows 10 x64. Don't see any logs to check / post.
Previous version ran fine.  Have no clue what to try.

**Comment by Xjph** [comment]
This is not the correct repository for reporting [issues with Observatory.](https://github.com/Xjph/ObservatoryCore/issues).

This is likely caused by an out of date plugin. If you are unable to resolve please re-open an issue at the above link and provide your ObservatoryErrorLog.txt and ObservatoryCrashLog.txt files from your documents folder.
